; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 66121277ce3c43a608c22fa4d784ef56f691080cc27188360d799cf1921e2c3f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_cvt_rn_satfinite_relu_e4m3x2_f16x2(i32 %packed) {
  %result = call i16 asm "cvt.rn.satfinite.relu.e4m3x2.f16x2 $0, $1;", "=h,r"(i32 %packed)
  ret i16 %result
}
